
import "./globals.css";
// import Link from "next/link";


export const metadata = {
  title: "Google",
  description: "Generated by Anila Ahmed",
};

export default function RootLayout({children}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        
      {children}
      </body>
    </html>
  );
}
